import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs/app-beta"
import Providers from "./providers"
import Header from "./header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body className="mx-12 lg:mx-96">
            <Header />
            {children}
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  )
}
