import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs/app-beta"
import Header from "./header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="mx-12 lg:mx-64">
          <Header />
          {children}
        </body>
      </ClerkProvider>
    </html>
  )
}
